apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
type: Opaque
stringData:
  HIVE_TOKEN: {{ .Values.hiveToken | quote }}
